# Generated by Django 4.2.3 on 2023-07-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_productselection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productselection',
            name='selected_at',
        ),
        migrations.AddField(
            model_name='productselection',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
