# Generated by Django 4.2.3 on 2023-07-09 17:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_productselection_unique_user_product'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productselection',
            name='unique_user_product',
        ),
        migrations.AlterUniqueTogether(
            name='productselection',
            unique_together={('user', 'product')},
        ),
    ]
